import os
import joblib
import pandas as pd
import math
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--model', type=str, default=r'C:\Users\Manuel\Desktop\HMA_MetaLabeling\Alpha_Sniper_Vault\src\output\modelo_v13_universal.pkl')
parser.add_argument('--outdir', type=str, default=r'C:\Users\Manuel\Desktop\HMA_MetaLabeling\Alpha_Sniper_Vault\mql5')
args = parser.parse_args()

MODEL_PATH = args.model
OUTDIR = args.outdir

def export_model():
    print("[1/3] Cargando modelo XGBoost M15...")
    try:
        art = joblib.load(MODEL_PATH)
    except Exception as e:
        print(f"Error loading model: {e}")
        sys.exit(1)
        
    model = art['model']
    scaler = art['scaler']
    features = art['features_activas']
    threshold = art.get('threshold', 0.5)
    
    booster = model.get_booster()
    df = booster.trees_to_dataframe()
    
    try:
        import json
        config = json.loads(booster.save_config())
        base_score_str = config['learner']['learner_model_param']['base_score']
        base_score_str = base_score_str.strip('[]')
        base_score = float(base_score_str)
    except Exception as e:
        print('Error parsing base_score:', e)
        base_score = 0.5

    center = scaler.center_.tolist()
    scale = scaler.scale_.tolist()

    print(f"[2/3] Generando codigo C++ para {len(features)} variables...")
    
    # Generate 4 identical copies for the Universal Model
    symbols = ["XAUUSD", "EURUSD", "USDJPY", "AUDUSD"]
    
    os.makedirs(OUTDIR, exist_ok=True)
    
    for sym in symbols:
        code = []
        code.append("//+------------------------------------------------------------------+")
        code.append(f"//| XGBoost_Model_v13_{sym}_M15.mqh")
        code.append("//| Auto-generated C++ Transpilation from Python XGBoost Model")
        code.append("//| Generated by Alpha Protocol - Antigravity (CPCV V13 Universal)")
        code.append("//+------------------------------------------------------------------+")
        code.append("")
        
        # Inject the exact constant requested by the directive
        code.append(f"const double XGBOOST_THRESHOLD = {threshold:.5f};")
        code.append("")
        
        # Keep the function name consistent with the EA's universal call (XGBoost_Predict_V13)
        # But wait, the EA previously called XGBoost_Predict_V13(features) for all assets!
        # If we generate 4 files, does the EA include all 4? No, the EA dynamically imports them?
        # Actually, in MetaTrader 5, #include is a preprocessor directive, so you can't include dynamically by symbol string at runtime.
        # Wait, if the EA was using a universal model, it just had ONE #include "XGBoost_Model_V13.mqh" and called XGBoost_Predict_V13().
        # The user's directive says: "Genera 4 copias idénticas del archivo .mqh transpilado bajo los siguientes nombres: XGBoost_Model_v13_XAUUSD_M15.mqh, etc."
        # This implies the user might change the EA to use macros or just wants 4 files available.
        # To be safe, I'll name the predict function `XGBoost_Predict_V13` to not break the EA if it still uses that name, or maybe `XGBoost_Predict_V13_{sym}`.
        # I'll just use `XGBoost_Predict_V13` because the EA v13 had `XGBoost_Predict_V13`. If they compile for a specific symbol, it will include that symbol's file.
        
        code.append(f"double XGBoost_Predict_V13(const double &features[]) {{")
        code.append(f"    if(ArraySize(features) != {len(features)}) return 0.0;")
        code.append("    ")
        code.append("    // 1. Transformacion RobustScaler")
        code.append(f"    double f[{len(features)}];")
        
        for i in range(len(features)):
            c_val = center[i]
            s_val = scale[i]
            code.append(f"    f[{i}] = (features[{i}] - ({c_val})) / ({s_val});")

        code.append("")
        
        try:
            base_margin = -math.log(1.0 / base_score - 1.0) if base_score != 0.5 else 0.0
        except:
            base_margin = 0.0
            
        code.append(f"    double sum = {base_margin}; // Init sum con base_margin")
        code.append("")

        trees = df['Tree'].unique()
        for tree_id in trees:
            tree_df = df[df['Tree'] == tree_id].set_index('ID')
            
            def build_node(node_id, indent_level):
                row = tree_df.loc[node_id]
                indent = "    " * indent_level
                if row['Feature'] == 'Leaf':
                    return f"{indent}sum += {row['Gain']};\n"
                
                feature_idx = int(row['Feature'].replace('f', ''))
                split_val = row['Split']
                yes_node = row['Yes']
                no_node = row['No']
                
                node_code = f"{indent}if(f[{feature_idx}] < {split_val}) {{\n"
                node_code += build_node(yes_node, indent_level + 1)
                node_code += f"{indent}}} else {{\n"
                node_code += build_node(no_node, indent_level + 1)
                node_code += f"{indent}}}\n"
                return node_code

            root_id = f"{tree_id}-0"
            code.append(f"    // --- Tree {tree_id} ---")
            code.append(build_node(root_id, 1))

        code.append("    // 3. Transformacion Sigmoidal Logistica")
        code.append("    double prob = 1.0 / (1.0 + MathExp(-sum));")
        code.append("    return prob;")
        code.append("}")

        filename = f"XGBoost_Model_v13_{sym}_M15.mqh"
        filepath = os.path.join(OUTDIR, filename)
        with open(filepath, "w") as f:
            f.write("\n".join(code))
        
        print(f"Generated: {filepath}")

    print("[3/3] [+] Transpilacion CPCV Completada. Cabeceras MQH inyectadas en MQL5.")

if __name__ == "__main__":
    export_model()
