import os

base_dir = r'C:\Users\Manuel\Desktop\HMA_MetaLabeling'

readme_content = """# HMA Meta-Labeling Project (Archived) ⚰️

![Status](https://img.shields.io/badge/Status-Archived%20%2F%20Post--Mortem-red)
![Type](https://img.shields.io/badge/Type-Quantitative%20Research-blue)

This repository contains the rigorous quantitative research, machine learning framework, and ultimate post-mortem of an algorithmic trading strategy based on the **Hull Moving Average (HMA)** combined with **XGBoost Meta-Labeling**.

> **⚠️ WARNING:** This strategy failed Out-of-Sample (OOS) validation and is structurally unprofitable. This repository has been open-sourced strictly for educational purposes to demonstrate advanced Walk-Forward validation, the dangers of over-optimization, and how to properly kill a trading strategy before risking capital.

## 📂 Repository Structure

- `/docs`: Extensive documentation, methodologies, and the quantitative autopsy.
  - [Post Mortem (Why the strategy failed)](docs/POST_MORTEM.md)
  - [Methodology (ML pipeline & validation)](docs/METHODOLOGY.md)
- `/src`: Cleaned source code.
  - `/mql5`: The MT5 Expert Advisors (Strategy chassis & feature extractor).
  - `/python`: The core Machine Learning pipeline.
- `/research_archive`: History of iterations, patches, failed experiments, and data pipelines.

## 🧠 Key Takeaways
1. **Beta vs. Alpha:** A long-only strategy performing well during a massive secular bull market (e.g., Gold 2023-2026) is capturing Market Beta, not Alpha.
2. **The MT5 Cartesian Bug:** Appending to CSV files in MetaTrader 5 without clearing them causes overlapping Cartesian products when merging features and labels, leading to fake machine learning metrics.
3. **Purged Walk-Forward ML:** Using a strict *Time-Based Rolling Purged Cross-Validation* destroyed the strategy's edge, proving that the HMA indicator lacks predictive power out-of-sample in Forex.

## 🤝 Collaboration
Feel free to fork this repository. While the HMA chassis was discarded, the **XGBoost Meta-Labeling Pipeline** and **MQL5 Extractor architecture** are highly valuable and can be adapted to test Mean Reversion or Volatility-based structural inefficiencies.
"""

post_mortem_content = """# ⚰️ POST MORTEM: The HMA Meta-Labeling Failure

## 1. Executive Summary
After rigorous quantitative validation, the **HMA (Hull Moving Average) + VPivots** strategy generated by StrategyQuant was definitively incinerated. Despite applying state-of-the-art machine learning (XGBoost Meta-Labeling), institutional risk filters, and asymmetric trend-following exits, the strategy consistently lost money in Out-Of-Sample (OOS) data.

**Final Verdict:** The system's perceived edge was a product of severe curve-fitting (over-optimization) to historical data. It possesses no structural Alpha.

---

## 2. The Illusion of the "Golden" Backtest (Beta vs Alpha)
Initially, the base model showed a spectacular 45-degree equity curve on the `XAUUSD` (Gold) from 2023 to 2026. 

**What went wrong?**
We mistook Beta for Alpha. The system was biased to Long trades. Between 2023 and 2026, Gold experienced a historic secular bull run. Any random long-only bot would have made money. However, when the XGBoost model evaluated the technical indicators (ADX, ATR, Keltner) to predict the outcome of specific trades, the AUC collapsed to `0.46` (worse than random chance). The indicators were not driving the wins; the macroeconomic trend was.

When we looked at the curve *before* the bull market (2021-2022), the strategy suffered devastating drawdowns. 

---

## 3. The MT5 "Cartesian Bug" (Data Contamination)
During the extraction phase, we encountered a critical data engineering flaw in MQL5:
* MT5 resets `Ticket` IDs every time the Strategy Tester is restarted.
* The EA logged `Features` to one CSV (which it successfully overwrote each run) but logged `Deals` to another CSV using `FILE_READ|FILE_WRITE` **without seeking or truncating**. 
* This appended new runs on top of old runs. When Python inner-joined Features and Deals by `Ticket ID`, it created a Cartesian Product. A single trade was mapped to 4 different overlapping profits from previous runs, creating a schizophrenic dataset and hallucinated AUC scores of ~0.52.

**The Fix:** We implemented forced file-deletion via external scripts prior to extraction, ensuring perfect 1:1 mapping.

---

## 4. The Institutional Shields (Operation Rescue)
To give the strategy a fair fight against the market, we removed the fixed Take Profit (1:1 RR) that castrates trend-following systems, and injected:
1. **Dynamic Spread Filter:** Blocked entries if Spread > 25% of H1 ATR.
2. **Directional Purge:** Strict Long-Only execution.
3. **Regime Filter:** Only trade if Daily ADX > 25.
4. **Asymmetric Exit:** Removed static TP and implemented a 3x ATR Dynamic Trailing Stop to let profits run.

---

## 5. The Final Nail in the Coffin (Rolling Walk-Forward)
Even with infinite upside potential, the strategy failed the ultimate test: **Time-Based Rolling Purged Cross-Validation**.
* Train on 24 months -> Predict the next 6 months (OOS) -> Slide window -> Repeat.
* **OOS Total Trades:** 107
* **OOS Win Rate:** 50.47%
* **OOS Profit Factor:** 0.89 (Net Loss: -$10,930)

**Why? Death by a Thousand Cuts.** The HMA crosses are structurally late. In non-trending or highly volatile years (2018, 2022, 2026), the Trailing Stop was repeatedly hit due to mean-reversion, destroying the profits generated during trending years.

## 6. Lessons for Quant Researchers
1. **Never trust In-Sample Equity Curves**, especially on highly trending assets.
2. **Always evaluate Asymmetry:** A trend-following model must be tested with unlimited Risk/Reward ratios.
3. **Machine Learning is a Filter, not a Savior:** XGBoost cannot find an edge if the underlying mechanical signals are noise.
"""

methodology_content = """# 🔬 METHODOLOGY: Meta-Labeling Framework

## 1. The Core Architecture
This project utilizes the **Meta-Labeling** paradigm proposed by Marcos López de Prado in *Advances in Financial Machine Learning*. 
* **Model 1 (Primary Model):** A standard algorithmic chassis (MQL5 EA based on HMA crossovers) that identifies trading opportunities (Entries & Exits) and sizes positions using the Kelly Criterion.
* **Model 2 (Meta-Model):** A Machine Learning algorithm (XGBoost) that observes the market state at the time of Model 1's signal and predicts the probability of the trade being profitable. It acts as a binary filter (0 = Skip, 1 = Execute).

## 2. Feature Engineering
When Model 1 triggers a signal, the EA extracts the following macro and micro-structural features into a CSV:
1. `Keltner_Bandwidth_H4`
2. `ATR_Ratio_H1_D1`
3. `ADX_Value_H4`
4. `ADX_Slope_H4`
5. `Dist_EMA200_H4`
6. `Bollinger_Width_H1`
7. `Daily_Exhaustion`

## 3. Data Pipeline & Labeling
* Features are logged in MT5 (`XGBoost_Features_M1_Symbol.csv`).
* The final trade outcomes (Profits) are logged in a Deals file (`Pipeline_Extractor_M1_Symbol.csv`).
* Python merges these files on `Ticket_ID`.
* **Labeling:** Trades with Profit > 0 are labeled `1` (True Positive). Trades with Profit < 0 are labeled `0` (False Positive).

## 4. Time-Based Rolling Purged Cross-Validation
To prevent Data Leakage (lookahead bias) and Overfitting, we evaluate the XGBoost model using a strict continuous Walk-Forward approach:
1. **Train Window:** 24 months of data.
2. **Purge:** 7 days removed to prevent autocorrelation between train and test boundaries.
3. **Test Window (Out-Of-Sample):** 6 months of data.
4. **Embargo:** 5 days removed after the test set before the next training block begins.

This simulates realistic production deployment where an algorithm is re-trained periodically but only trades the unknown future.
"""

# Escribir los archivos
with open(os.path.join(base_dir, 'README.md'), 'w', encoding='utf-8') as f:
    f.write(readme_content)

with open(os.path.join(base_dir, 'docs', 'POST_MORTEM.md'), 'w', encoding='utf-8') as f:
    f.write(post_mortem_content)

with open(os.path.join(base_dir, 'docs', 'METHODOLOGY.md'), 'w', encoding='utf-8') as f:
    f.write(methodology_content)

print("Documentacion exhaustiva (Markdown) generada exitosamente.")
