import os
import joblib
import pandas as pd
import math
import sys
import json

OUTDIR = r'C:\Users\Manuel\Desktop\HMA_MetaLabeling\Alpha_Sniper_Vault\mql5'
os.makedirs(OUTDIR, exist_ok=True)
SYMS = ['XAUUSD','EURUSD','USDJPY','AUDUSD']
MODEL_DIR = r'C:\Users\Manuel\Desktop\HMA_MetaLabeling\Alpha_Sniper_Vault\src\output'

def export_sym(sym):
    path = os.path.join(MODEL_DIR, f'modelo_v16_1_per_asset_{sym}.pkl')
    try:
        art = joblib.load(path)
    except:
        print(f"[{sym}] Model not found.")
        return
        
    model = art['model']
    scaler = art['scaler']
    features = art['features_activas']
    threshold = art.get('threshold', 0.5)
    
    booster = model.get_booster()
    df = booster.trees_to_dataframe()
    
    try:
        config = json.loads(booster.save_config())
        base_score_str = config['learner']['learner_model_param']['base_score'].strip('[]')
        base_score = float(base_score_str)
    except:
        base_score = 0.5

    center = scaler.center_.tolist()
    scale = scaler.scale_.tolist()
    
    func_name = f"XGBoost_Predict_v16_{sym}"
    const_name = f"XGBOOST_THRESHOLD_{sym}"
    
    code = f"""//+------------------------------------------------------------------+
//| XGBoost_Model_v16_{sym}_M15.mqh
//| Auto-generated C++ Transpilation from Python XGBoost Model
//| Generated by Alpha Protocol - Antigravity (CPCV V16.1 Per-Asset)
//+------------------------------------------------------------------+

const double {const_name} = {threshold:.5f};

double {func_name}(const double &features[]) {{
    if(ArraySize(features) != {len(features)}) {{
        Print("Error: Feature count mismatch in {sym}. Expected {len(features)}");
        return 0.0;
    }}

    double f[{len(features)}];
"""
    for i in range(len(features)):
        code += f"    f[{i}] = (features[{i}] - ({center[i]:.5f})) / ({scale[i]:.5f});\n"

    try:
        base_margin = -math.log(1.0 / base_score - 1.0) if base_score != 0.5 else 0.0
    except:
        base_margin = 0.0

    code += "\n    double sum = " + str(base_margin) + ";\n\n"

    trees = df['Tree'].unique()
    for tree_id in trees:
        tree_df = df[df['Tree'] == tree_id].set_index('ID')
        
        def build_node(node_id, indent_level):
            row = tree_df.loc[node_id]
            indent = "    " * indent_level
            if row['Feature'] == 'Leaf':
                return f"{indent}sum += {row['Gain']};\n"
            
            feat_val = row['Feature']
            if str(feat_val).startswith('f') and str(feat_val)[1:].isdigit():
                feature_idx = int(str(feat_val).replace('f', ''))
            else:
                feature_idx = features.index(feat_val)

            split_val = row['Split']
            yes_node = row['Yes']
            no_node = row['No']
            
            node_code = f"{indent}if(f[{feature_idx}] < {split_val}) {{\n"
            node_code += build_node(yes_node, indent_level + 1)
            node_code += f"{indent}}} else {{\n"
            node_code += build_node(no_node, indent_level + 1)
            node_code += f"{indent}}}\n"
            return node_code

        root_id = f"{tree_id}-0"
        code += f"    // --- Tree {tree_id} ---\n"
        code += build_node(root_id, 1)
        code += "\n"

    code += """    // Sigmoid function
    double probability = 1.0 / (1.0 + MathExp(-sum));
    return probability;
}
"""
    # Overwrite the existing V16 files so EA doesn't need to be modified again
    out_path = os.path.join(OUTDIR, f'XGBoost_Model_v16_{sym}_M15.mqh')
    with open(out_path, 'w') as f:
        f.write(code)
    print(f"[{sym}] Exported to {out_path} (Threshold: {threshold:.4f})")

if __name__ == '__main__':
    for sym in SYMS:
        export_sym(sym)