import os
import joblib
import pandas as pd
import math
import sys

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--model', type=str, default='C:/Users/Manuel/Desktop/HMA_MetaLabeling/Alpha_Sniper_Vault/src/output/modelo_m15_universal.pkl')
parser.add_argument('--output', type=str, default='C:/Users/Manuel/Desktop/HMA_MetaLabeling/Alpha_Sniper_Vault/mql5/XGBoost_Model.mqh')
args = parser.parse_args()

MODEL_PATH = args.model
OUTPUT_PATH = args.output

def export_model():
    print("[1/3] Cargando modelo XGBoost M15...")
    try:
        art = joblib.load(MODEL_PATH)
    except Exception as e:
        print(f"Error loading model: {e}")
        sys.exit(1)
        
    model = art['model']
    scaler = art['scaler']
    features = art['features_activas']
    
    booster = model.get_booster()
    df = booster.trees_to_dataframe()
    
    # Extract base score or fallback
    try:
        import json
        config = json.loads(booster.save_config())
        base_score_str = config['learner']['learner_model_param']['base_score']
        base_score_str = base_score_str.strip('[]')
        base_score = float(base_score_str)
    except Exception as e:
        print('Error parsing base_score:', e)
        base_score = 0.5

    center = scaler.center_.tolist()
    scale = scaler.scale_.tolist()

    print(f"[2/3] Generando codigo C++ para {len(features)} variables...")
    code = []
    code.append("//+------------------------------------------------------------------+")
    code.append("//| XGBoost_Model.mqh")
    code.append("//| Auto-generated C++ Transpilation from Python XGBoost Model")
    code.append("//| Generated by Alpha Protocol - Antigravity")
    code.append("//+------------------------------------------------------------------+")
    code.append("")
    filename = os.path.basename(args.output)
    symbol_name = ""
    if "Model_" in filename:
        symbol_name = "_" + filename.split("Model_")[1].split("_")[0]

    code.append(f"double XGBoost_Predict{symbol_name}(const double &features[]) {{")
    code.append(f"    if(ArraySize(features) != {len(features)}) return 0.0;")
    code.append("    ")
    code.append("    // 1. Transformacion RobustScaler")
    code.append(f"    double f[{len(features)}];")
    
    for i in range(len(features)):
        c_val = center[i]
        s_val = scale[i]
        code.append(f"    f[{i}] = (features[{i}] - ({c_val})) / ({s_val});")

    code.append("")
    
    # Init sum with base_margin. Logistic link uses log(odds)
    try:
        base_margin = -math.log(1.0 / base_score - 1.0) if base_score != 0.5 else 0.0
    except:
        base_margin = 0.0
        
    code.append(f"    double sum = {base_margin}; // Init sum con base_margin")
    code.append("")

    trees = df['Tree'].unique()
    for tree_id in trees:
        tree_df = df[df['Tree'] == tree_id].set_index('ID')
        
        def build_node(node_id, indent_level):
            row = tree_df.loc[node_id]
            indent = "    " * indent_level
            if row['Feature'] == 'Leaf':
                return f"{indent}sum += {row['Gain']};\n"
            
            feature_idx = int(row['Feature'].replace('f', ''))
            split_val = row['Split']
            yes_node = row['Yes']
            no_node = row['No']
            
            node_code = f"{indent}if(f[{feature_idx}] < {split_val}) {{\n"
            node_code += build_node(yes_node, indent_level + 1)
            node_code += f"{indent}}} else {{\n"
            node_code += build_node(no_node, indent_level + 1)
            node_code += f"{indent}}}\n"
            return node_code

        root_id = f"{tree_id}-0"
        code.append(f"    // --- Tree {tree_id} ---")
        code.append(build_node(root_id, 1))

    code.append("    // 3. Transformacion Sigmoidal Logistica")
    code.append("    double prob = 1.0 / (1.0 + MathExp(-sum));")
    code.append("    return prob;")
    code.append("}")

    print(f"[3/3] Escribiendo archivo MQL5 en: {OUTPUT_PATH}")
    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(code))
    print("[+] Transpilacion Completada. Latencia Cero lista para produccion.")

if __name__ == "__main__":
    export_model()

