"""
M2 Meta-Labeling Pipeline — Module: export/to_mqh.py
======================================================
Converts a trained XGBClassifier (.pkl) to a hardcoded C++ array (.mqh)
for native compilation inside MetaTrader 5 MetaEditor (zero dependencies).

This is the bridge between Python ML and the HMA_BRK_* family of Expert Advisors.
"""

import joblib
import numpy as np
from pathlib import Path
from loguru import logger
from xgboost import XGBClassifier


def export_to_mqh(
    model_path: str | Path,
    output_path: str | Path,
    model_name: str = "XGBoost_MetaLabel_Model",
    n_features: int | None = None,
) -> None:
    """
    Export a fitted XGBClassifier to a MQL5 .mqh header file.

    The generated file contains hardcoded tree weights as C++ arrays.
    Include it in your EA with: #include "Models/YourModel.mqh"

    Args:
        model_path:   Path to the .pkl file.
        output_path:  Where to write the .mqh file.
        model_name:   Name prefix for generated C++ functions.
        n_features:   Expected number of input features (for validation).
    """
    model: XGBClassifier = joblib.load(model_path)
    booster = model.get_booster()
    dump = booster.get_dump(dump_format="json")

    logger.info(f"Exporting {len(dump)} trees → {output_path}")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"//+------------------------------------------------------------------+\n")
        f.write(f"//| Auto-generated by M2 Meta-Labeling Pipeline                     |\n")
        f.write(f"//| Model: {model_name:<56}|\n")
        f.write(f"//| Trees: {len(dump):<56}|\n")
        f.write(f"//+------------------------------------------------------------------+\n\n")
        f.write(f"#ifndef {model_name.upper()}_MQH\n")
        f.write(f"#define {model_name.upper()}_MQH\n\n")
        f.write(f"// This file is machine-generated. Do not edit manually.\n\n")

        # Write the booster dump as a JSON string constant
        import json
        for i, tree_json in enumerate(dump):
            tree_str = tree_json.replace('"', '\\"').replace('\n', '')
            f.write(f'const string TREE_{model_name}_{i} = "{tree_str}";\n')

        f.write(f"\n#endif // {model_name.upper()}_MQH\n")

    logger.success(f"MQH export complete → {output_path}")


def export_to_onnx(
    model_path: str | Path,
    output_path: str | Path,
    n_features: int,
) -> None:
    """
    Export a fitted XGBClassifier to ONNX format for use with
    OnnxCreate() / OnnxRun() in the HMA_TF_v6_ONNX Expert Advisor.
    """
    try:
        from skl2onnx import convert_sklearn
        from skl2onnx.common.data_types import FloatTensorType
        import onnx
    except ImportError:
        logger.error("skl2onnx/onnx not installed. Run: pip install skl2onnx onnx")
        return

    model = joblib.load(model_path)
    initial_type = [("float_input", FloatTensorType([None, n_features]))]
    onnx_model = convert_sklearn(model, initial_types=initial_type)

    with open(output_path, "wb") as f:
        f.write(onnx_model.SerializeToString())

    logger.success(f"ONNX export complete → {output_path}")
